#!/bin/bash
# Cross-implementation test: C encoder -> Python decoder
# This test verifies that fragments generated by the C encoder can be
# decoded by the reference Python decoder implementation.

set -e

# Change to project root directory
cd "$(dirname "$0")/.."

echo "=========================================="
echo "Cross-Implementation Test"
echo "C Encoder -> Python Decoder"
echo "=========================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Build the C fragment printer if needed
if [ ! -f tests/test_print_fragments ]; then
    echo -e "${YELLOW}Building C fragment printer...${NC}"
    make test-print-fragments
fi

# Create a test output directory
TEST_OUTPUT_DIR="tests/test_cross_output"
mkdir -p "$TEST_OUTPUT_DIR"

# Find all test case files
TEST_FILES=(tests/test_cases/*.UR_object.txt)

if [ ${#TEST_FILES[@]} -eq 0 ]; then
    echo -e "${RED}ERROR: No test case files found${NC}"
    exit 1
fi

echo -e "Found ${BLUE}${#TEST_FILES[@]}${NC} test case files\n"

# Create a Python test script to decode the fragments
cat > "$TEST_OUTPUT_DIR/test_decode.py" << 'PYTHON_SCRIPT'
#!/usr/bin/env python3
import sys
import os

# Add the Python implementation to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'foundation-ur-py', 'src'))

from ur.ur_decoder import URDecoder

def test_decode(fragments_file, expected_cbor_hex=None):
    """Decode fragments generated by C encoder."""
    # Read fragments
    with open(fragments_file, 'r') as f:
        fragments = [line.strip() for line in f if line.strip()]

    print(f"Total fragments available: {len(fragments)}")

    decoder = URDecoder()
    parts_used = 0

    for i, fragment in enumerate(fragments, 1):
        try:
            decoder.receive_part(fragment)
            parts_used += 1

            if decoder.is_complete():
                print(f"Decoding complete after {parts_used} parts (of {len(fragments)} available)")

                if decoder.is_success():
                    result = decoder.result_message()
                    print(f"✓ Decoding successful!")
                    print(f"  Type: {result.type}")
                    print(f"  Data size: {len(result.cbor)} bytes")

                    # Verify against expected if provided
                    if expected_cbor_hex:
                        actual_hex = result.cbor.hex()
                        if actual_hex == expected_cbor_hex:
                            print(f"✓ Data matches expected output")
                            return True
                        else:
                            print(f"✗ Data mismatch!")
                            print(f"  Expected: {expected_cbor_hex[:100]}...")
                            print(f"  Got:      {actual_hex[:100]}...")
                            return False

                    return True
                else:
                    print("✗ Decoding completed but not successful")
                    return False
        except Exception as e:
            print(f"✗ Error processing fragment {i}: {e}")
            return False

    print(f"✗ Failed to decode after {parts_used} parts")
    print(f"  Expected part count: {decoder.expected_part_count()}")
    return False

if __name__ == "__main__":
    fragments_file = sys.argv[1]
    expected_hex = sys.argv[2] if len(sys.argv) > 2 else None
    success = test_decode(fragments_file, expected_hex)
    sys.exit(0 if success else 1)
PYTHON_SCRIPT

chmod +x "$TEST_OUTPUT_DIR/test_decode.py"

# Test each file individually
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0

for test_file in "${TEST_FILES[@]}"; do
    TOTAL_TESTS=$((TOTAL_TESTS + 1))

    TEST_NAME=$(basename "$test_file" .UR_object.txt)
    echo -e "${YELLOW}========================================${NC}"
    echo -e "${YELLOW}Test $TOTAL_TESTS: $TEST_NAME${NC}"
    echo -e "${YELLOW}========================================${NC}"

    # Read expected CBOR from the test file
    EXPECTED_HEX=$(cat "$test_file" | sed 's/hex://' | tr -d '[:space:]')

    # Generate fragments for this specific test file
    echo -e "${BLUE}Step 1: Generating fragments with C encoder...${NC}"
    FRAGMENT_FILE="$TEST_OUTPUT_DIR/${TEST_NAME}_fragments.txt"
    ./tests/test_print_fragments "$test_file" 2> "$TEST_OUTPUT_DIR/${TEST_NAME}_stderr.txt" > "$FRAGMENT_FILE"

    FRAGMENT_COUNT=$(wc -l < "$FRAGMENT_FILE")

    if [ "$FRAGMENT_COUNT" -eq 0 ]; then
        echo -e "${RED}ERROR: No fragments generated${NC}"
        cat "$TEST_OUTPUT_DIR/${TEST_NAME}_stderr.txt"
        FAILED_TESTS=$((FAILED_TESTS + 1))
        continue
    fi

    echo -e "Generated ${GREEN}$FRAGMENT_COUNT${NC} fragments"

    # Show encoder info
    grep -E "(CBOR data size:|Single part:|Sequence length:)" "$TEST_OUTPUT_DIR/${TEST_NAME}_stderr.txt" | sed 's/^/  /' || true

    # Show sample fragments
    echo -e "\nSample fragments:"
    head -n 2 "$FRAGMENT_FILE" | sed 's/^/  /'
    if [ "$FRAGMENT_COUNT" -gt 2 ]; then
        echo "  ..."
    fi

    # Decode with Python
    echo -e "\n${BLUE}Step 2: Decoding with Python decoder...${NC}"
    if python3 "$TEST_OUTPUT_DIR/test_decode.py" "$FRAGMENT_FILE" "$EXPECTED_HEX"; then
        echo -e "${GREEN}✓ Test PASSED${NC}\n"
        PASSED_TESTS=$((PASSED_TESTS + 1))
    else
        echo -e "${RED}✗ Test FAILED${NC}\n"
        FAILED_TESTS=$((FAILED_TESTS + 1))
    fi
done

# Summary
echo -e "${YELLOW}========================================${NC}"
echo -e "${YELLOW}Test Summary${NC}"
echo -e "${YELLOW}========================================${NC}"
echo -e "Total tests:  $TOTAL_TESTS"
echo -e "Passed:       ${GREEN}$PASSED_TESTS${NC}"
echo -e "Failed:       ${RED}$FAILED_TESTS${NC}"
echo -e "${YELLOW}========================================${NC}"

if [ "$FAILED_TESTS" -eq 0 ]; then
    echo -e "${GREEN}✓ ALL CROSS-IMPLEMENTATION TESTS PASSED!${NC}"
    exit 0
else
    echo -e "${RED}✗ Some tests failed${NC}"
    echo -e "Debug info saved in: $TEST_OUTPUT_DIR/"
    exit 1
fi
