#!/bin/bash
# Cross-implementation test: C encoder -> Python decoder
# This test verifies that fragments generated by the C encoder can be
# decoded by the reference Python decoder implementation and converted back to PSBT.

set -e

# Change to project root directory
cd "$(dirname "$0")/../.."

echo "=========================================="
echo "Cross-Implementation Test"
echo "C Encoder -> Python Decoder (PSBT)"
echo "=========================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Build the C PSBT fragment printer if needed
if [ ! -f tests/cross_implementation_tests/test_print_psbt_fragments ]; then
    echo -e "${YELLOW}Building C PSBT fragment printer...${NC}"
    make -s test-print-psbt-fragments || {
        echo -e "${RED}Failed to build PSBT fragment printer${NC}"
        echo -e "Please run: make test-print-psbt-fragments"
        exit 1
    }
fi

# Create a test output directory
TEST_OUTPUT_DIR="tests/cross_implementation_tests/test_cross_output"
mkdir -p "$TEST_OUTPUT_DIR"

# Find all PSBT test case files
TEST_FILES=(tests/test_cases/PSBTs/*.psbt.bin)

if [ ${#TEST_FILES[@]} -eq 0 ]; then
    echo -e "${RED}ERROR: No PSBT test case files found${NC}"
    exit 1
fi

echo -e "Found ${BLUE}${#TEST_FILES[@]}${NC} PSBT test files\n"

# Create a Python test script to decode the fragments and verify using urtypes
cat > "$TEST_OUTPUT_DIR/test_decode.py" << 'PYTHON_SCRIPT'
#!/usr/bin/env python3
import sys
import os

# Add the Python implementation to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..', 'foundation-ur-py', 'src'))

from ur.ur_decoder import URDecoder
try:
    from urtypes.crypto.psbt import PSBT
    URTYPES_AVAILABLE = True
except ImportError:
    print("Warning: urtypes not available, will only verify decoding")
    URTYPES_AVAILABLE = False

def test_decode(fragments_file, expected_psbt_file=None):
    """Decode fragments generated by C encoder and verify using urtypes."""
    # Read fragments
    with open(fragments_file, 'r') as f:
        fragments = [line.strip() for line in f if line.strip()]

    print(f"Total fragments available: {len(fragments)}")

    decoder = URDecoder()
    parts_used = 0

    for i, fragment in enumerate(fragments, 1):
        try:
            decoder.receive_part(fragment)
            parts_used += 1

            if decoder.is_complete():
                print(f"Decoding complete after {parts_used} parts (of {len(fragments)} available)")

                if decoder.is_success():
                    result = decoder.result_message()
                    print(f"✓ Decoding successful!")
                    print(f"  Type: {result.type}")
                    print(f"  CBOR size: {len(result.cbor)} bytes")

                    # Verify using urtypes if available
                    if URTYPES_AVAILABLE and expected_psbt_file:
                        try:
                            # Decode CBOR to PSBT using urtypes
                            psbt = PSBT.from_cbor(result.cbor)
                            decoded_psbt_bytes = psbt.data

                            print(f"  Decoded PSBT size: {len(decoded_psbt_bytes)} bytes")

                            # Read expected PSBT bytes
                            with open(expected_psbt_file, 'rb') as f:
                                expected_psbt_bytes = f.read()

                            print(f"  Expected PSBT size: {len(expected_psbt_bytes)} bytes")

                            # Compare
                            if decoded_psbt_bytes == expected_psbt_bytes:
                                print(f"✓ PSBT bytes match expected!")
                                return True
                            else:
                                print(f"✗ PSBT bytes mismatch!")
                                # Show where first difference is
                                for idx, (a, b) in enumerate(zip(decoded_psbt_bytes, expected_psbt_bytes)):
                                    if a != b:
                                        print(f"  First difference at byte {idx}: expected 0x{b:02x}, got 0x{a:02x}")
                                        break
                                return False
                        except Exception as e:
                            print(f"✗ Error verifying with urtypes: {e}")
                            import traceback
                            traceback.print_exc()
                            return False

                    # If urtypes not available or no expected file, just verify decoding worked
                    return True
                else:
                    print("✗ Decoding completed but not successful")
                    return False
        except Exception as e:
            print(f"✗ Error processing fragment {i}: {e}")
            import traceback
            traceback.print_exc()
            return False

    print(f"✗ Failed to decode after {parts_used} parts")
    print(f"  Expected part count: {decoder.expected_part_count()}")
    return False

if __name__ == "__main__":
    fragments_file = sys.argv[1]
    expected_psbt_file = sys.argv[2] if len(sys.argv) > 2 else None
    success = test_decode(fragments_file, expected_psbt_file)
    sys.exit(0 if success else 1)
PYTHON_SCRIPT

chmod +x "$TEST_OUTPUT_DIR/test_decode.py"

# Test each file individually
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0

for test_file in "${TEST_FILES[@]}"; do
    TOTAL_TESTS=$((TOTAL_TESTS + 1))

    TEST_NAME=$(basename "$test_file" .psbt.bin)
    echo -e "${YELLOW}========================================${NC}"
    echo -e "${YELLOW}Test $TOTAL_TESTS: $TEST_NAME${NC}"
    echo -e "${YELLOW}========================================${NC}"

    # Generate fragments for this specific test file
    echo -e "${BLUE}Step 1: Generating fragments with C encoder...${NC}"
    FRAGMENT_FILE="$TEST_OUTPUT_DIR/${TEST_NAME}_fragments.txt"
    ./tests/cross_implementation_tests/test_print_psbt_fragments "$test_file" 2> "$TEST_OUTPUT_DIR/${TEST_NAME}_stderr.txt" > "$FRAGMENT_FILE"

    FRAGMENT_COUNT=$(wc -l < "$FRAGMENT_FILE")

    if [ "$FRAGMENT_COUNT" -eq 0 ]; then
        echo -e "${RED}ERROR: No fragments generated${NC}"
        cat "$TEST_OUTPUT_DIR/${TEST_NAME}_stderr.txt"
        FAILED_TESTS=$((FAILED_TESTS + 1))
        continue
    fi

    echo -e "Generated ${GREEN}$FRAGMENT_COUNT${NC} fragments"

    # Show encoder info
    grep -E "(PSBT size:|CBOR size:|Single part:|Sequence length:)" "$TEST_OUTPUT_DIR/${TEST_NAME}_stderr.txt" | sed 's/^/  /' || true

    # Show sample fragments
    echo -e "\nSample fragments:"
    head -n 2 "$FRAGMENT_FILE" | sed 's/^/  /'
    if [ "$FRAGMENT_COUNT" -gt 2 ]; then
        echo "  ..."
    fi

    # Decode with Python
    echo -e "\n${BLUE}Step 2: Decoding with Python decoder and verifying with urtypes...${NC}"
    if python3 "$TEST_OUTPUT_DIR/test_decode.py" "$FRAGMENT_FILE" "$test_file"; then
        echo -e "${GREEN}✓ Test PASSED${NC}\n"
        PASSED_TESTS=$((PASSED_TESTS + 1))
    else
        echo -e "${RED}✗ Test FAILED${NC}\n"
        FAILED_TESTS=$((FAILED_TESTS + 1))
    fi
done

# Summary
echo -e "${YELLOW}========================================${NC}"
echo -e "${YELLOW}Test Summary${NC}"
echo -e "${YELLOW}========================================${NC}"
echo -e "Total tests:  $TOTAL_TESTS"
echo -e "Passed:       ${GREEN}$PASSED_TESTS${NC}"
echo -e "Failed:       ${RED}$FAILED_TESTS${NC}"
echo -e "${YELLOW}========================================${NC}"

if [ "$FAILED_TESTS" -eq 0 ]; then
    echo -e "${GREEN}✓ ALL CROSS-IMPLEMENTATION TESTS PASSED!${NC}"
    exit 0
else
    echo -e "${RED}✗ Some tests failed${NC}"
    echo -e "Debug info saved in: $TEST_OUTPUT_DIR/"
    exit 1
fi
